version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - database
    volumes:
      - /home/ubuntu/gwjeong.com/db/data:/var/lib/postgresql/data
      - /home/ubuntu/gwjeong.com/db/config/postgres.conf:/etc/postgresql/postgres.conf
    user: 1000:100

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - pgadmin
    ports:
      - 8088:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

networks:
  database:
    external:
       name: database
  pgadmin:
    external:
       name: pgadmin
